### ISSUE TITLE
没用啊

### ISSUE THREAD

**Issue by vvvvvvvvave** [wjlin0/riverPass#2]
大佬看看咋回事

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/364f3317-5ad0-4d78-b32d-3df528ae64cf">

**Comment by wjlin0** [comment]
看看你的burp 代理设置

**Comment by vvvvvvvvave** [comment]
> 看看你的burp 代理设置

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/e35df56f-96c7-4530-8829-ce3919c00ec6">

<img width="706" alt="image" src="https://github.com/user-attachments/assets/87296ff0-c6a8-4a70-886c-f9e3a03c333d">

<img width="513" alt="image" src="https://github.com/user-attachments/assets/83e5b7f7-bc09-470c-84c3-6a984ba21bdb">

**Comment by wjlin0** [comment]
浏览器没有关闭吧

**Comment by wjlin0** [comment]
![QQ_1729739783952](https://github.com/user-attachments/assets/20b650e5-c0d9-4203-b195-51a7593426b5)
这里是 Req-Flag

**Comment by wjlin0** [comment]
![QQ_1729739836223](https://github.com/user-attachments/assets/26f2d3fd-c554-457f-80d6-2062c91e63df)
删掉这个参数

**Comment by wjlin0** [comment]
刚测试了 没问题  修改我上面说的两个问题 你再看看呢？
![QQ_1729739871257](https://github.com/user-attachments/assets/b7d51298-c1ba-40c2-ab1c-4fb62fefe4f7)

**Comment by vvvvvvvvave** [comment]
> ![QQ_1729739783952](https://private-user-images.githubusercontent.com/91306421/379531605-20b650e5-c0d9-4203-b195-51a7593426b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDAxMTQsIm5iZiI6MTcyOTczOTgxNCwicGF0aCI6Ii85MTMwNjQyMS8zNzk1MzE2MDUtMjBiNjUwZTUtYzBkOS00MjAzLWIxOTUtNTFhNzU5MzQyNmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAzMTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjlmYmIwMGJhYTMzYmI5ODQ5YWNkMTM0ZmZhZjRhNTA2NWY1OTVjNDBhNWU1OGIzODFlNDg3OTRmMjJlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vdjT_VidioNZTXrKP6ax4LNdshKu10Uwk88Y9ExYsQ8) 这里是 Req-Flag

好了，大佬，哈哈
