### ISSUE TITLE
师傅请问有的网站不行是为啥呢？

### ISSUE THREAD

**Issue by UIWP0** [wjlin0/riverPass#3]
按照readme配置163是正常的，但是有的网站不行，例如：
访问/123456 证明是瑞数WAF
![image](https://github.com/user-attachments/assets/2c760e06-3528-4f60-8f16-cf5af769b694)
按照要求配置
![image](https://github.com/user-attachments/assets/ac1c5632-860e-4d89-9303-cf709e528cb5)
![image](https://github.com/user-attachments/assets/57f0d86b-80a6-4d7f-ab2d-c3826e384b3f)
![image](https://github.com/user-attachments/assets/341e5171-e503-4522-bda2-14fc518d2423)
然后数据包
![image](https://github.com/user-attachments/assets/c1c2ac85-2836-4e93-893c-8abcc5124abc)
添加参数
![image](https://github.com/user-attachments/assets/5339a05e-c85f-462d-9380-d4939fc75631)
报错报错500

**Comment by UIWP0** [comment]
没事了师傅，有时候不行，得等一会在试试就好了 :>

**Comment by wjlin0** [comment]
> 没事了师傅，有时候不行，得等一会在试试就好了 :>

这个需要和浏览器 websocket 的链接一直在才行

**Comment by UIWP0** [comment]
> > 没事了师傅，有时候不行，得等一会在试试就好了 :>
> 
> 这个需要和浏览器 websocket 的链接一直在才行

另外有个问题师傅，就是通过你的工具实现了绕过WAF，但是只能是在浏览器访问状态抓包绕过，那如果我现在逆向出了加密的JS代码，想通过脚本实现爆破，但是工具访问肯定412，如何解决呢 😄
